# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Here’s a breakdown of the hierarchy:

# stages:
#  - stage:
#    Jobs:
#     Steps:
#      - task:

trigger:
- main

pool:
  name: host-jay
  demands:
    - Agent.Name -equals host-agent

stages:
  - stage: restore
    jobs:
      - job: restoreJob
        steps:
          - task: DotNetCoreCLi@1
            displayName: Restore
            inputs:
              command: 'restore'
              feedsToUse: 'select'
              vstsfeed: 'my-vsts-feed'
          
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: build
              projects: '**/*.csproj' #path of project
              arguments: '--configuration $(buildConfiguration)'

          - task: DotNetCoreCLI@2
            displayName: Publish
            inputs:
              command: publish
              publishWebProjects: True
              arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
              zipAfterPublish: True
              
          - task: PublishPipelineArtifact@0
            displayName: Upload
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'Web-app'
